[project]
name = "capm"
version = "0.1.0"
description = "Capital Asset Pricing Model"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "yfinance==0.2.46",
    "matplotlib==3.9.2"
]
